server:
  port: 8888
spring:
  application:
    name: spring-cloud-system
  datasource:
      url: jdbc:mysql://localhost:3306/spring-cloud-system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      hikari:
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:mappers/*/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#dubbo:
#  protocol:
#    port: 20889
#    name: dubbo
#  registry:
#    address: spring-cloud://127.0.0.1:8848
#  cloud:
#    subscribed-services: product
#  application:
#    name: admin