server:
  port: 9999
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - StripPrefix=2
      routes:
        - id: route-spring-cloud-system
          uri: lb://spring-cloud-system
          predicates:
            - Path=/api/system/**